### ISSUE TITLE
Theme does not use Google Sans

### ISSUE THREAD

**Issue by paw-lu** [chrismessina/alfred-theme-google#1]
<img width="702" alt="Screen Shot 2021-01-05 at 1 35 19 PM" src="https://user-images.githubusercontent.com/30049606/103701583-21a4d180-4f5b-11eb-987c-d9c67518d919.png">

Even after Google Sans is installed using the link provided, the theme does make use of the font.

<img width="488" alt="Screen Shot 2021-01-05 at 1 35 41 PM" src="https://user-images.githubusercontent.com/30049606/103701604-29647600-4f5b-11eb-8a3e-9563243313fc.png">

This might because the link you provide installs itself as `Product Sans`, while the Alfred theme is looking for `Google Sans`?

<img width="724" alt="Screen Shot 2021-01-05 at 1 35 49 PM" src="https://user-images.githubusercontent.com/30049606/103701611-2d909380-4f5b-11eb-8947-01489e0e67ba.png">

Thanks for the great theme!

**Comment by chrismessina** [comment]
Hmm! Oh wow, you're right! The link goes to [a page for Google Sans](https://www.cufonfonts.com/font/google-sans) but indeed, the font that's downloaded is Product Sans! These fonts are nearly identical — but perhaps for ™ reasons, Cufon had to offer the non-branded version?

Anyway, I've remedied the issue by creating a variant that uses Product Sans instead! Thanks for the report!

https://github.com/chrismessina/alfred-theme-google/releases/tag/v1.0.1
